version: '3.8'
services:
  ftdc-victoriametrics:
    image: docker.io/victoriametrics/victoria-metrics:v1.104.0
    container_name: "ftdc-victoriametrics"
    hostname: "ftdc-victoriametrics"
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8086"
      - "--dedup.minScrapeInterval=60s"
      - "--maxInsertRequestSize=3GB"
    ports:
      - "28428:8428"
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=zelmario
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=percona
      - DOCKER_INFLUXDB_INIT_BUCKET=ftdc
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ftdc
    networks:
      - ftdc 
    volumes:
      # # - /data/container/app/ftdc/victoriametrics:/storage
      # - '--storageDataPath=/storage'    # Set the storage path
      - type: tmpfs
        target: /storage
        tmpfs:
          size: 1000000000

  grafana:
    # image: grafana/grafana:latest
    # image: docker.io/grafana/grafana:latest
    image: docker.io/grafana/grafana-oss:11.2.2
    container_name: "ftdc-grafana"
    hostname: "ftdc-grafana"
    cap_drop:
      - ALL
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - CHECK_ORIGIN=false
    links:
      - ftdc-victoriametrics
    networks:
      - ftdc 
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/main.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards/:/etc/grafana/provisioning/dashboards/

  metrics-processor:
    build: .
    cap_drop:
      - ALL
    volumes:
      # - ./diagnostic.data:/diagnostic.data
      - /data/container/app/ftdc/diagnostic.data:/diagnostic.data
    depends_on:
      - ftdc-victoriametrics
    links:
      - ftdc-victoriametrics
    networks:
      - ftdc 
    entrypoint: ["/scripts/run_scripts.sh", "/diagnostic.data"]

networks:
  ftdc: {}
